import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { 
  Search, 
  Filter, 
  Plus, 
  ChevronRight, 
  Sparkles,
  X
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { RiskBadge } from '../common/RiskBadge';

export const InventoryDashboard = () => {
  const { batches, addBatch, setSelectedBatchId } = useApp();
  const navigate = useNavigate();

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRiskFilter, setSelectedRiskFilter] = useState('ALL');
  const [isFifoComparisonActive, setIsFifoComparisonActive] = useState(true);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);

  const [newBatch, setNewBatch] = useState({
    id: '',          // empty = auto-generated by backend
    produce: 'Tomato',
    variety: '',
    palletCount: 10,
    weightKg: '',
    estimatedValue: '',
    storageAgeDays: 1.0,
    initialShelfLifeDays: 14.0,
    zone: '',
    targetTemp: '',
    defaultDestination: ''
  });


  const handleAddSubmit = (e) => {
    e.preventDefault();
    addBatch(newBatch);
    setIsAddModalOpen(false);
  };

  const filteredBatches = batches.filter(batch => {
    const matchesSearch = 
      batch.produce.toLowerCase().includes(searchQuery.toLowerCase()) ||
      batch.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      batch.zone.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesRisk = selectedRiskFilter === 'ALL' || batch.riskLevel === selectedRiskFilter;
    return matchesSearch && matchesRisk;
  });

  const displayBatches = [...filteredBatches].sort((a, b) => {
    if (isFifoComparisonActive) {
      const riskWeight = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1 };
      if (riskWeight[b.riskLevel] !== riskWeight[a.riskLevel]) {
        return riskWeight[b.riskLevel] - riskWeight[a.riskLevel];
      }
      return a.remainingShelfLifeHours - b.remainingShelfLifeHours;
    } else {
      return new Date(a.arrivalDate) - new Date(b.arrivalDate);
    }
  });

  const filterColors = {
    ALL: 'bg-white/10 text-white border-white/20',
    CRITICAL: 'bg-rose-900/60 text-rose-300 border-rose-700/50',
    HIGH: 'bg-amber-900/50 text-amber-300 border-amber-700/50',
    MEDIUM: 'bg-blue-900/50 text-blue-300 border-blue-700/50',
    LOW: 'bg-emerald-900/50 text-emerald-300 border-emerald-700/50',
  };

  return (
    <div className="space-y-6">
      
      {/* Header & FIFO Comparison Toggle */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-[#18261a]/80 p-6 rounded-2xl border border-emerald-800/40 shadow-lg backdrop-blur-sm">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-indigo-900/50 text-indigo-300 border border-indigo-700/50">
              Batches
            </span>
            <span className="text-xs text-emerald-300/50 font-medium">Active Warehouse Stock</span>
          </div>
          <h1 className="text-2xl font-black text-white tracking-tight">
            Manage &amp; Inspect Batches
          </h1>
          <p className="text-xs text-emerald-200/50 mt-0.5">
            Search, filter by risk, and drill into any batch.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          
          {/* FIFO vs RipePulse Toggle */}
          <div className="flex items-center bg-black/30 p-1 rounded-xl border border-white/10 text-xs font-bold">
            <button
              onClick={() => setIsFifoComparisonActive(false)}
              className={`px-3 py-1.5 rounded-lg transition-all ${
                !isFifoComparisonActive 
                  ? 'bg-white/10 text-white shadow border border-white/20' 
                  : 'text-emerald-300/50 hover:text-white'
              }`}
            >
              Naive FIFO (Age)
            </button>
            <button
              onClick={() => setIsFifoComparisonActive(true)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition-all ${
                isFifoComparisonActive 
                  ? 'bg-emerald-600 text-white shadow' 
                  : 'text-emerald-300/50 hover:text-white'
              }`}
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>RipePulse AI (Risk)</span>
            </button>
          </div>

          <button
            onClick={() => setIsAddModalOpen(true)}
            className="flex items-center gap-1.5 px-4 py-2 bg-amber-400 hover:bg-amber-300 text-slate-950 font-bold text-xs rounded-xl shadow-md shadow-amber-400/20 transition-all active:scale-95"
          >
            <Plus className="w-4 h-4" />
            <span>Add Batch</span>
          </button>
        </div>
      </div>

      {/* FIFO vs FEFO Educational Banner */}
      <div className={`p-4 rounded-xl border text-xs transition-all ${
        isFifoComparisonActive 
          ? 'bg-emerald-900/30 border-emerald-700/40 text-emerald-200' 
          : 'bg-amber-900/30 border-amber-700/40 text-amber-200'
      }`}>
        <div className="flex items-start gap-2.5">
          <Sparkles className="w-4 h-4 mt-0.5 shrink-0 text-emerald-400" />
          <div>
            <strong className="font-bold">
              {isFifoComparisonActive
                ? 'Active Strategy: RipePulse Dynamic Risk-Based Prioritization'
                : 'Active Strategy: Traditional First-In First-Out (FIFO)'}
            </strong>
            <p className="mt-0.5 text-emerald-200/60">
              {isFifoComparisonActive
                ? 'Batches are prioritized by predicted Remaining Shelf Life and thermal decay rate. Even though Strawberries #BAT-9042 arrived 4 days after Apples #BAT-8711, thermal abuse elevated its risk, requiring priority intervention.'
                : 'Traditional FIFO blindly prioritizes older batches (e.g. Avocado #BAT-8833) for dispatch even though they have 110h safe buffer, while newly arrived Strawberries with thermal abuse are neglected and spoil.'}
            </p>
          </div>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="bg-[#18261a]/80 p-4 rounded-xl border border-emerald-800/40 shadow-sm backdrop-blur-sm flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 text-emerald-400/40 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search by produce, ID, zone..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs rounded-lg bg-black/30 border border-emerald-800/50 text-white placeholder-emerald-300/30 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500"
          />
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto w-full md:w-auto">
          <span className="text-xs font-semibold text-emerald-400/50 mr-2 flex items-center gap-1">
            <Filter className="w-3.5 h-3.5" /> Risk:
          </span>
          {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((lvl) => (
            <button
              key={lvl}
              onClick={() => setSelectedRiskFilter(lvl)}
              className={`px-3 py-1 rounded-lg text-xs font-bold transition-all border ${
                selectedRiskFilter === lvl
                  ? filterColors[lvl]
                  : 'bg-white/5 text-emerald-300/50 border-white/10 hover:bg-white/10 hover:text-white'
              }`}
            >
              {lvl}
            </button>
          ))}
        </div>
      </div>

      {/* Batch Inventory Table */}
      <div className="bg-[#18261a]/80 rounded-2xl border border-emerald-800/40 shadow-sm overflow-hidden backdrop-blur-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-emerald-200/70">
            <thead className="bg-black/20 border-b border-white/10 text-[11px] font-bold uppercase tracking-wider text-emerald-400/50">
              <tr>
                <th className="px-5 py-3.5">Produce & Batch</th>
                <th className="px-5 py-3.5">Chamber & Volume</th>
                <th className="px-5 py-3.5">Current Telemetry</th>
                <th className="px-5 py-3.5">Shelf-Life Index (SLI)</th>
                <th className="px-5 py-3.5">Predicted RSL</th>
                <th className="px-5 py-3.5">Waste Risk</th>
                <th className="px-5 py-3.5">Route Feasibility</th>
                <th className="px-5 py-3.5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {displayBatches.map((batch) => {
                const isCritical = batch.riskLevel === 'CRITICAL';
                const isFeasible = batch.currentRoute?.isFeasible;

                return (
                  <tr 
                    key={batch.id} 
                    className="hover:bg-white/5 transition-colors group cursor-pointer"
                    onClick={() => {
                      setSelectedBatchId(batch.id);
                      navigate(`/batches/${batch.id}`);
                    }}
                  >
                    
                    {/* Produce & ID */}
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-3">
                        <span className="text-2xl">{batch.icon}</span>
                        <div>
                          <div className="font-extrabold text-white text-sm group-hover:text-emerald-300 transition-colors">
                            {batch.produce}
                          </div>
                          <div className="flex items-center gap-2 text-[11px] text-emerald-300/40 mt-0.5">
                            <span className="font-mono font-semibold text-emerald-300/60">{batch.id}</span>
                            <span>•</span>
                            <span>{batch.variety}</span>
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* Zone & Quantity */}
                    <td className="px-5 py-4">
                      <span className="font-medium text-white block">{batch.zone}</span>
                      <span className="text-[11px] text-emerald-300/40">
                        {batch.palletCount} Pallets ({batch.weightKg.toLocaleString()} kg)
                      </span>
                    </td>

                    {/* Telemetry */}
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-3">
                        <div>
                          <span className="text-[10px] text-emerald-400/40 block font-medium">Temp</span>
                          <span className={`font-bold ${batch.currentTemp > batch.baselineTemp + 2 ? 'text-rose-400' : 'text-white'}`}>
                            {batch.currentTemp}°C
                          </span>
                        </div>
                        <div>
                          <span className="text-[10px] text-emerald-400/40 block font-medium">VOC</span>
                          <span className={`font-bold ${batch.currentVoc > 2.0 ? 'text-amber-400' : 'text-white'}`}>
                            {batch.currentVoc} ppm
                          </span>
                        </div>
                      </div>
                    </td>

                    {/* SLI Bar */}
                    <td className="px-5 py-4">
                      <div className="w-28">
                        <div className="flex justify-between items-center text-[11px] font-bold mb-1">
                          <span className="text-white">{batch.sli}%</span>
                          <span className="text-[10px] text-emerald-400/40">{batch.confidenceScore}% conf</span>
                        </div>
                        <div className="w-full bg-white/10 rounded-full h-2 overflow-hidden border border-white/5">
                          <div
                            className={`h-full rounded-full transition-all duration-500 ${
                              batch.sli < 35 ? 'bg-rose-500' : batch.sli < 65 ? 'bg-amber-500' : 'bg-emerald-500'
                            }`}
                            style={{ width: `${batch.sli}%` }}
                          />
                        </div>
                      </div>
                    </td>

                    {/* RSL */}
                    <td className="px-5 py-4">
                      <span className={`font-extrabold text-sm ${isCritical ? 'text-rose-400' : 'text-white'}`}>
                        {batch.remainingShelfLifeHours} Hours
                      </span>
                      <span className="text-[10px] text-emerald-400/40 block font-medium">
                        Decay: {batch.decayRateFactor}x normal
                      </span>
                    </td>

                    {/* Risk Badge */}
                    <td className="px-5 py-4">
                      <RiskBadge level={batch.riskLevel} />
                    </td>

                    {/* Route Feasibility */}
                    <td className="px-5 py-4">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold border ${
                        isFeasible 
                          ? 'bg-emerald-900/50 text-emerald-300 border-emerald-700/50' 
                          : 'bg-rose-900/50 text-rose-300 border-rose-700/50'
                      }`}>
                        {isFeasible ? 'Feasible' : 'Infeasible'}
                      </span>
                      <span className="text-[10px] text-emerald-400/40 block mt-0.5">
                        {batch.currentRoute?.transitDurationHours}h transit
                      </span>
                    </td>

                    {/* Actions */}
                    <td className="px-5 py-4 text-right">
                      <div className="flex items-center justify-end gap-2" onClick={(e) => e.stopPropagation()}>
                        <Link
                          to={`/batches/${batch.id}`}
                          className="p-1.5 rounded-lg border border-white/10 hover:bg-white/10 text-emerald-300/60 hover:text-white transition-colors"
                          title="View Telemetry Graphs"
                        >
                          <ChevronRight className="w-4 h-4" />
                        </Link>

                        {!isFeasible && (
                          <Link
                            to="/routing"
                            className="px-2.5 py-1 bg-amber-400 hover:bg-amber-300 text-slate-950 font-bold text-[11px] rounded-lg shadow transition-all"
                          >
                            Reroute
                          </Link>
                        )}
                      </div>
                    </td>

                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Add Batch Modal */}
      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
          <div className="bg-[#18261a] rounded-2xl border border-emerald-800/50 shadow-2xl shadow-black/60 max-w-lg w-full p-6">
            <div className="flex items-center justify-between pb-4 border-b border-white/10">
              <div>
                <h3 className="text-lg font-extrabold text-white">Register New Produce Batch</h3>
                <p className="text-xs text-emerald-200/50">Add inbound harvest lot to automated shelf-life tracking</p>
              </div>
              <button 
                onClick={() => setIsAddModalOpen(false)}
                className="p-1 rounded-lg text-emerald-300/50 hover:text-white hover:bg-white/10"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleAddSubmit} className="space-y-4 mt-4">
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Batch ID</label>
                  <input
                    type="text"
                    required
                    value={newBatch.id}
                    onChange={(e) => setNewBatch({ ...newBatch, id: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white font-mono font-bold focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    placeholder="e.g. BAT-9042"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Produce Name</label>
                  <select
                    value={newBatch.produce}
                    onChange={(e) => {
                      const p = e.target.value;
                      const isTomato = p.toLowerCase().includes('tomato');
                      setNewBatch({
                        ...newBatch,
                        produce: p,
                        variety: isTomato ? 'Hybrid' : 'Commercial Grade A',
                        targetTemp: isTomato ? 18.2 : 2.0,
                        storageAgeDays: isTomato ? 4.0 : 1.0,
                        initialShelfLifeDays: isTomato ? 21.0 : 7.0,
                        zone: isTomato ? 'Controlled Atmosphere B' : 'Deep Chill Bay A'
                      });
                    }}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white font-bold focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  >
                    <option value="Tomato">🍅 Tomato (Hybrid / Roma)</option>
                    <option value="Organic Strawberries">🍓 Organic Strawberries</option>
                    <option value="Honeycrisp Apples">🍎 Honeycrisp Apples</option>
                    <option value="Baby Spinach">🥬 Baby Spinach</option>
                    <option value="Bell Peppers">🫑 Bell Peppers</option>
                    <option value="Valencia Oranges">🍊 Valencia Oranges</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Variety / Grade</label>
                  <input
                    type="text"
                    required
                    value={newBatch.variety}
                    onChange={(e) => setNewBatch({ ...newBatch, variety: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white placeholder-emerald-300/30 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    placeholder="e.g. Hybrid"
                  />
                </div>
              </div>

              <div className="grid grid-cols-4 gap-3">
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Weight (kg)</label>
                  <input
                    type="number"
                    required
                    value={newBatch.weightKg}
                    onChange={(e) => {
                      const w = parseFloat(e.target.value) || 0;
                      setNewBatch({ ...newBatch, weightKg: w, estimatedValue: Math.round(w * 4.5) });
                    }}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Pallet Count</label>
                  <input
                    type="number"
                    required
                    value={newBatch.palletCount}
                    onChange={(e) => setNewBatch({ ...newBatch, palletCount: parseInt(e.target.value) || 1 })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Storage Age (days)</label>
                  <input
                    type="number"
                    step="0.5"
                    required
                    value={newBatch.storageAgeDays}
                    onChange={(e) => setNewBatch({ ...newBatch, storageAgeDays: parseFloat(e.target.value) || 0 })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Initial Life (days)</label>
                  <input
                    type="number"
                    step="1"
                    required
                    value={newBatch.initialShelfLifeDays}
                    onChange={(e) => setNewBatch({ ...newBatch, initialShelfLifeDays: parseFloat(e.target.value) || 1 })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Chamber Zone</label>
                  <select
                    value={newBatch.zone}
                    onChange={(e) => setNewBatch({ ...newBatch, zone: e.target.value })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  >
                    <option value="Controlled Atmosphere B">Controlled Atmosphere B (15.0°C)</option>
                    <option value="Deep Chill Bay A">Deep Chill Bay A (2.0°C)</option>
                    <option value="Dry Ambient Bay C">Dry Ambient Bay C (12.0°C)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Target Temp (°C)</label>
                  <input
                    type="number"
                    step="0.1"
                    value={newBatch.targetTemp}
                    onChange={(e) => setNewBatch({ ...newBatch, targetTemp: parseFloat(e.target.value) })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-emerald-300/70 mb-1">Est. Value ($)</label>
                  <input
                    type="number"
                    required
                    value={newBatch.estimatedValue}
                    onChange={(e) => setNewBatch({ ...newBatch, estimatedValue: parseFloat(e.target.value) || 0 })}
                    className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-emerald-300/70 mb-1">Destination Route</label>
                <input
                  type="text"
                  value={newBatch.defaultDestination}
                  onChange={(e) => setNewBatch({ ...newBatch, defaultDestination: e.target.value })}
                  className="w-full px-3 py-2 text-xs rounded-lg bg-black/40 border border-emerald-800/50 text-white placeholder-emerald-300/30 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  placeholder="e.g. Delhi Terminal Market"
                />
              </div>


              <div className="pt-4 border-t border-white/10 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsAddModalOpen(false)}
                  className="px-4 py-2 rounded-xl text-xs font-bold text-emerald-300/60 hover:bg-white/5 hover:text-white transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-md transition-all"
                >
                  Confirm Ingestion
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
};
