import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bell, RefreshCw } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { PageHeader } from '../components/common/PageHeader';
import { EmptyState, LoadingState, ErrorState } from '../components/common/EmptyState';
import { display } from '../utils/format';

const SEV_FILTERS = ['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'UNRESOLVED'];

const SEV_STYLE = {
  CRITICAL: { pill: 'border-rose-600/50 bg-rose-600/15 text-rose-300',    dot: 'bg-rose-400',    border: 'border-rose-800/40' },
  HIGH:     { pill: 'border-orange-600/40 bg-orange-600/10 text-orange-300', dot: 'bg-orange-400', border: 'border-orange-800/30' },
  MEDIUM:   { pill: 'border-amber-600/40 bg-amber-600/10 text-amber-300',  dot: 'bg-amber-400',   border: 'border-amber-800/30' },
  LOW:      { pill: 'border-emerald-600/40 bg-emerald-600/10 text-emerald-300', dot: 'bg-emerald-400', border: 'border-emerald-800/40' },
};

export const AlertsPage = () => {
  const {
    alerts, acknowledgeAlert, resolveAlert, dataLoading, backendOnline,
    refreshData, errorMessage, showNotification, setSelectedBatchId,
  } = useApp();

  const [sevFilter, setSevFilter] = useState('ALL');

  const filtered = useMemo(() => {
    if (sevFilter === 'ALL') return alerts;
    if (sevFilter === 'UNRESOLVED') return alerts.filter((a) => a.status === 'UNRESOLVED');
    return alerts.filter((a) => a.severity === sevFilter);
  }, [alerts, sevFilter]);

  const unresolved = alerts.filter((a) => a.status === 'UNRESOLVED').length;

  if (dataLoading) return <LoadingState label="Loading alerts…" />;
  if (backendOnline === false) return <ErrorState message={errorMessage} onRetry={refreshData} />;

  const onAck = async (id) => {
    try {
      await acknowledgeAlert(id);
    } catch (err) {
      showNotification('Acknowledge failed', err.message || 'Backend did not update the alert.', 'error');
    }
  };

  const onResolve = async (id) => {
    try {
      await resolveAlert(id);
    } catch (err) {
      showNotification('Resolve failed', err.message || 'Backend did not update the alert.', 'error');
    }
  };

  return (
    <div className="space-y-5">
      <PageHeader
        kicker="Alerts"
        title="Operational Alerts"
        subtitle="All alerts are generated by the backend AI engine. No mock data."
        actions={
          <div className="flex items-center gap-2">
            {unresolved > 0 && (
              <span className="rounded-full border border-rose-600/40 bg-rose-600/10 px-2.5 py-1 text-xs font-black text-rose-400">
                {unresolved} Unresolved
              </span>
            )}
            <button type="button" onClick={refreshData}
              className="inline-flex items-center gap-1.5 rounded-xl border border-emerald-800/40 px-3 py-2 text-xs font-bold text-emerald-300 hover:bg-white/5">
              <RefreshCw className="h-3.5 w-3.5" /> Refresh
            </button>
          </div>
        }
      />

      {/* ── Severity filter chips ── */}
      <div className="flex flex-wrap items-center gap-1.5">
        {SEV_FILTERS.map((f) => (
          <button
            key={f}
            type="button"
            onClick={() => setSevFilter(f)}
            className={`rounded-full border px-3 py-1 text-[11px] font-bold transition-colors ${
              sevFilter === f
                ? (SEV_STYLE[f]?.pill || 'border-emerald-500 bg-emerald-500/20 text-emerald-300')
                : 'border-white/10 text-emerald-200/40 hover:text-white hover:border-emerald-700/40'
            }`}
          >
            {f === 'ALL' ? `All (${alerts.length})` :
             f === 'UNRESOLVED' ? `Unresolved (${unresolved})` : f}
          </button>
        ))}
      </div>

      {/* ── Alert cards ── */}
      {filtered.length === 0 ? (
        <EmptyState
          title={alerts.length === 0 ? 'NO ALERTS' : 'NO MATCHING ALERTS'}
          message={alerts.length === 0
            ? 'No backend-generated alerts are currently available.'
            : 'Try a different filter.'}
          icon={Bell}
        />
      ) : (
        <div className="space-y-3">
          {filtered.map((a) => {
            const style = SEV_STYLE[a.severity] || SEV_STYLE.LOW;
            return (
              <article
                key={a.id}
                className={`rounded-2xl border ${style.border} bg-[#18261a]/70 p-5 transition-colors`}
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="flex items-start gap-3 min-w-0 flex-1">
                    {/* Severity dot */}
                    <div className={`mt-1.5 h-2 w-2 rounded-full shrink-0 ${style.dot}`} />
                    <div className="min-w-0">
                      {/* Severity badge + batch + time */}
                      <div className="flex flex-wrap items-center gap-2 mb-1">
                        <span className={`rounded-full border px-2.5 py-0.5 text-[10px] font-black uppercase ${style.pill}`}>
                          {a.severity}
                        </span>
                        <span className="font-mono text-xs font-bold text-emerald-400">{display(a.batchId)}</span>
                        <span className="text-[11px] text-emerald-200/40">{display(a.timestamp)}</span>
                      </div>
                      <h3 className="text-sm font-black text-white">{display(a.title)}</h3>
                      <p className="mt-1 text-sm text-emerald-200/65 leading-relaxed">{display(a.message)}</p>
                      {a.actionRequired && a.actionRequired !== 'None' && (
                        <p className="mt-2 text-[11px] font-bold text-amber-300/80">
                          ⚡ Required: {a.actionRequired}
                        </p>
                      )}
                      <div className="mt-2 flex items-center gap-2">
                        <span className={`text-[10px] font-black uppercase tracking-wider ${
                          a.status === 'UNRESOLVED' ? 'text-rose-400' :
                          a.status === 'ACKNOWLEDGED' ? 'text-amber-400' : 'text-emerald-400/50'
                        }`}>
                          ● {a.status}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Action buttons */}
                  <div className="flex gap-2 shrink-0">
                    <Link
                      to={`/batches/${a.batchId}`}
                      onClick={() => setSelectedBatchId(a.batchId)}
                      className="rounded-xl border border-emerald-700/40 px-3 py-1.5 text-xs font-bold text-emerald-200 hover:border-emerald-500 hover:text-white transition-colors"
                    >
                      View Batch
                    </Link>
                    {a.status === 'UNRESOLVED' && (
                      <button
                        type="button"
                        onClick={() => onAck(a.id)}
                        className="rounded-xl bg-emerald-500/90 px-3 py-1.5 text-xs font-bold text-slate-950 hover:bg-emerald-400 transition-colors"
                      >
                        Acknowledge
                      </button>
                    )}
                    {a.status === 'ACKNOWLEDGED' && (
                      <button
                        type="button"
                        onClick={() => onResolve(a.id)}
                        className="rounded-xl border border-emerald-600/60 bg-emerald-600/15 px-3 py-1.5 text-xs font-bold text-emerald-300 hover:bg-emerald-600/25 transition-colors"
                      >
                        ✓ Resolve
                      </button>
                    )}
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      )}

      {filtered.length > 0 && (
        <p className="text-center text-[11px] text-emerald-200/30">
          {filtered.length} alert{filtered.length !== 1 ? 's' : ''} shown · All generated by the backend
        </p>
      )}
    </div>
  );
};
